env:
  browser: true
parserOptions:
  ecmaVersion: 8
extends: 'eslint:recommended'
globals:
  "$": false
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - off
  semi:
    - error
    - always
  curly:
    - error
    - all
  no-console:
    - off
  no-undef:
    - error
  no-unused-vars:
    - error
  brace-style:
    - error
